---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-backup-b2-credentials
  namespace: longhorn-backup
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: AgAnBQT8jcYHMFKfSiJFTr5C/kkncllN5iz75Sn22s7lpEfLEdeNovSnIBmcniSg+LFye0wiUxLEgviXVc/HU80Eq8kdZvHQUi9u9m8UiM4fyWmGmh5g278XFflbWis1XYjPk/EY1H0ORIzfzNdracxGh/XOWYb2obIkhboWOVD5x8IrOUBkRLoL+ofUk/Ky6DWJH46VhSMPTvSqKA1pGu4YhKMw9BJBNFSadeFPxQKGoxhaph3cHbrz5yEfOqTSXSisa55EVZBcFkBUg4EihBUkSXHETt366EncyTUqvXJBlbrdzxtVFIHAYR61YwXR7Mg+n0guR6uZSqBQ7cVXFNReTEsPPAGe6eH7ss12GFAHdtZSL3ZmN9/7SesrC4h7Ty8dYoDXem1XtE/WcD+wDo6wgv49fYyv77HR1xzKjlxkW2MBw5NoGxX+vXsaHQQZFUrF3oTOUNuYdgCzRxMcRsOgqTPqGszo6z3accG8+B2jK8PrlkNI7tDqjlknseLgrABOKe+3aq4utKwAmwXABHWzpFIV0AIqnzHr1AL7/5DGQ5KdZwzgGXAVd5qHZiGVUvVXgQXYz7GdZPsvc5WdcLmPXRrJq75BNU5eYiiDTRyw5TUEVq7psdkuxGGGWB8k2dDYkhbbu+VK4SqmowGgkaDT+yoC+a76vvz9ffQgszPBLyImYnDlP9hOeGT+S7AmuGfdZlqKDTyWLNGmncHRNIlFbL9ws8IhqYfk
    AWS_SECRET_ACCESS_KEY: AgClLWBTviFmj6nkj+KbCzg9LkyR9bC0rVSf+RPp/+JgRaZNabPy1UsVv/AZt+Ur+nseWYSgbok14RKJlsAQH7yyKkCaVw+Us4xH9b7cjTGFF6m0+ji0J9XIiYPI0/gPHuarVHo/HObGoLpX2gZJUk0S52dYcLb8mI6oBi70HcSSehtjmPWEQ5F9oHrUMcPrXzkukzFYePJ2RlXcXSiSlZnzn860UdrNNJjQQDUmv4Sz7hUKyk4bYacC5GBVdoAiyNgsDdtjPVJh5IB+FR2uJ1kWO7+WecaTAZ0qJl67dNj1mL9BpZQ1V3VDwWRVQ56VOGnGIeJsIS6slBmxWX4vYFHr4oz7o81yTXVY8zQ+i0880gK3yWN0wfqqESD1L7CTBmiezofBws2D6ELaF7tufTebOQnfXOOrNN7etLaK2ZkE7pxYe1sQe4gqux8vyCMzHiWkqQ6RzT/JEta5NuOAe6PVfmk5g6xLA/S6+8J3Q+9rmO8D5xVi/K4a2Wn+Z/IHlyCQFoUYZKFwK2L1XVpV/C2X2yHjNapmizA2jJF+FDXVCujen/bS5VSGI6Tx+265u/DC9ywtDgSASAUAQJq9Zyn+qf3Zr16Z4faE+/eWx+rLz6rth/0D+VL7xrKLnY/mWQqL4DrKyQG20wVDcPA1f1fP32YMfFgeSNS9vjI8TXpWG85yA8pbjWy0oqaAHaEyBrh1bqUKI03fxcWF5rII3xoYXqdVCq2HbaZ4A1R9ys/w
  template:
    metadata:
      name: longhorn-backup-b2-credentials
      namespace: longhorn-backup
